version: '3.1'

services:

  consignment-cli:
    container_name: consignment-cli
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  user-cli:
    container_name: user-cli
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    container_name: consignment-service
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  vessel-service:
    container_name: vessel-service
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  user-service:
    container_name: user-service
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats:4222"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

  email-service:
    container_name: email-service
    build: ./email-service
    ports:
      - 50054:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats:4222"

  api-getway:
    container_name: api-getway
    build: ./api-getway
    ports:
      - 8080:8080
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_API_HANDLER: "rpc"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats:4222"
      MICRO_ADDRESS: ":8080"
      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: "OPTIONS"

  datastore:
    container_name: datastore
    image: mongo
    ports:
      - 27017:27017

  nats:
    container_name: nats
    image: nats
    ports:
      - 4222:4222
      - 8222:8222

  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
